# Docker Compose build file: docker-compose -f build.yml build_tools
version: "3.7"

services:
  build_tools:
    build:
      dockerfile: Dockerfile.test
      context: .
    volumes:
      - ./:/opt/docker-pi-hole
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: /opt/docker-pi-hole/build_tools.py
