name: Test & Build
on:
  push:
    branches:
      - master
      - dev
      - v*
      - beta-v*
      - release/*
    tags:
      - v*
  pull_request:

#env:
#  DOCKER_HUB_REPO: pihole

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
          ARCH: [amd64, armhf, arm64, i386]
          DEBIAN_VERSION: [buster]
    env:
      ARCH: ${{matrix.ARCH}}
      DEBIAN_VERSION: ${{matrix.DEBIAN_VERSION}}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Build images
        run: |
          echo "${{ secrets.DOCKERHUB_PASS }}" | docker login --username="${{ secrets.DOCKERHUB_USER }}" --password-stdin
          ./gh-actions-test.sh
