name: Test & Build
on:
  push:
    branches:
      - master
      - dev
      - v*
      - beta-v*
      - release/*
    tags:
      - v*
  pull_request:

#env:
#  DOCKER_HUB_REPO: pihole

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    env:
      ARCH: "amd64 arm64"
      DEBIAN_VERSION: "buster"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Build images
        run: |
          echo "${{ secrets.DOCKERHUB_PASS }}" | docker login --username="${{ secrets.DOCKERHUB_USER }}" --password-stdin
          ./gh-actions-vars.sh
          ./gh-actions-test.sh
          docker buildx ls
          docker buildx use pihole-build
          docker buildx inspect
