name: Test & Build
on:
  push:
    branches:
      - master
      - dev
      - v*
      - beta-v*
      # TODO @lightswitch05 REMOVE ME!
      - feature/introduce-debian-version-tags
  pull_request:

# TODO @lightswitch05 REMOVE ME!
# https://hub.docker.com/r/lightswitch05/pihole
env:
  DOCKER_HUB_REPO: lightswitch05

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ARCH: [amd64, armhf, arm64]
        DEBIAN_VERSION: [stretch, buster]
    env:
      ARCH: ${{matrix.ARCH}}
      DEBIAN_VERSION: ${{matrix.DEBIAN_VERSION}}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Run Tests
        run: |
          echo "Building ${ARCH}-${DEBIAN_VERSION}"
          ./gh-actions-test.sh
      - name: Upload gh-workspace
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v1
        with:
          name: gh-workspace
          path: .gh-workspace

  publish:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    needs: test-and-build
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Download workspace files
        uses: actions/download-artifact@v1
        with:
          name: gh-workspace
      - name: Tag and Publish
        run: |
          echo ${{ secrets.DOCKERHUB_PASS }} | docker login --username=$DOCKERHUB_USER --password-stdin
          ./gh-actions-deploy.sh
